name: "CI"

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          check-latest: true
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true
          add-job-summary: always

      - name: Run build lifecycle
        run: ./gradlew --no-daemon --stacktrace
